### ISSUE TITLE
oa2bibliometrix when author is NA

### ISSUE THREAD

**Issue by mmmaat** [ropensci/openalexR#110]
Hi, 

There is a bug in `oa2bibliometrix` when the author is unknown. For instance the work "W3125831892" is failing with the message `$ operator is invalid for atomic vectors`:

```R
library(openalexR)
oa_fetch(entity="works", id="W3125831892") %>% oa2bibliometrix()
```

This comes from this code block: https://github.com/ropensci/openalexR/blob/31ae05817ce9825a6df8b8f2839bcf02de34b600/R/oa2bibliometrix.R#L58-L67

Below is a quick fix I wrote (I'm a beginner in R so I do not PR, there's maybe a cleaner way of doing this):

```R
# Authors
  AU_info <- lapply(df$author, function(l) {
    if (length(l) == 1 && is.na(l)) {  # author is not defined
     AU <- ""
     C1 <- ""
     RP <- ""
     AU_UN <- ""
     AU_CO <- ""
    }
    else {
      AU <- au_collapse(l$au_display_name)
      C1 <- au_collapse(l$au_affiliation_raw)
      RP <- au_collapse(l$au_affiliation_raw[1])
      AU_UN <- au_collapse(l$institution_name)
      l$institution_country[is.na(l$institution_country)] <- "Not available"
      AU_CO <- au_collapse(countrycode[l$institution_country, 1])
    }
    
   list(AU = AU, RP = RP, C1 = C1, AU_UN = AU_UN, AU_CO = AU_CO)
  })
```

**Comment by trangdata** [comment]
Thank you for reporting @mmmaat. 💯 And thank you for sharing your workaround. My fix (added in #109) is very similar, except that I used the internal function `empty_list` to handle the NA case.
