### ISSUE TITLE
oa_snowball fails when OpenAlex ids change

### ISSUE THREAD

**Issue by tklebel** [ropensci/openalexR#113]
I have encountered an error when applying `tbl_graph` on output from `oa_snowball`. Below is a reprex that shows the issue.

`tbl_graph` fails because one of the edges points to a paper that is not contained in the set. This happens because one of the ids apparently changed in OpenAlex. This is the offending ID: https://api.openalex.org/works/W2008324369, which is referenced in the seed publication.

If you open it in the browser, it is redirected to https://api.openalex.org/works/W4246358555

I don't know whether this is expected behaviour from OpenAlex, but it would be great if `oa_snowball` could handle these cases.

``` r
library(openalexR)
library(tidygraph)
library(dplyr)

snowball_test <- oa_snowball(doi = "10.1371/journal.pone.0125208", verbose = TRUE)
#> Requesting url: https://api.openalex.org/works?filter=doi%3A10.1371%2Fjournal.pone.0125208
#> Getting 1 page of results with a total of 1 records...
#> Collecting all documents citing the target papers...
#> Requesting url: https://api.openalex.org/works?filter=cites%3AW2140232888
#> Getting 1 page of results with a total of 21 records...
#> Collecting all documents cited by the target papers...
#> Requesting url: https://api.openalex.org/works?filter=cited_by%3AW2140232888
#> Getting 1 page of results with a total of 27 records...

# We are gathering 27 references from the paper

as_tbl_graph(snowball_test)
#> Error in (function (edges, n = max(edges), directed = TRUE) : At core/constructors/basic_constructors.c:72 : Invalid (non-finite or NaN) vertex index when creating graph. Invalid value


nodes <- snowball_test$nodes

nodes %>% 
  filter(oa_input) %>% 
  pull(referenced_works) %>% 
  .[[1]] %>% 
  length()
#> [1] 28

# But the paper cites 28 works
```

<sup>Created on 2023-05-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by tklebel** [comment]
On second reflection, this does seem like a bug in the OpenAlex API. https://api.openalex.org/works?filter=cited_by%3AW2140232888 should handle these changed IDs properly.

**Comment by trangdata** [comment]
Great investigative work @tklebel! I posted a message on the OpenAlex google group (pending approval).

**Comment by trangdata** [comment]
I think this has been fixed in the OpenAlex database (at least in this particular example). I'm gonna go ahead and close this issue, but please re-open if similar cases come up!
