### ISSUE TITLE
The best way to do scholar level matching?

### ISSUE THREAD

**Issue by JeffreySmithA** [ropensci/openalexR#116]
Hi All,

Another question. What would be the best way to match scholars?

So for example, if I have a set of scholars in my dataset that are in the 'treated' group. How would I go about querying the API to find a 'control' group? By this I mean I have a set of criteria that I would like to attain such as:

1. A similar level of publications
2. The same subfield
3. Similar stock of citations

etc.

Any ideas would be much appreciated!

**Comment by trangdata** [comment]
Good question @JeffreySmithA. So the list of [filters for authors](https://docs.openalex.org/api-entities/authors/filter-authors) don't include subfield. If you need, say, 100 authors, what I would recommend you do is sample for 1000 authors with similar level of publications and citations (and whichever other filters you choose to use), and then, out of 1000, find the 100 authors with similarly ranked [x_concepts](https://docs.openalex.org/api-entities/authors/author-object#x_concepts).

Hth!

**Comment by JeffreySmithA** [comment]
Thank you... again!!!
