### ISSUE TITLE
Entity "works" field "is_oa" shall have multiple key-value pairs

### ISSUE THREAD

**Issue by yhan818** [ropensci/openalexR#134]
OpenAlex data "is_oa" has multiple key-value pairs. see  [ https://docs.openalex.org/how-to-use-the-api/get-lists-of-entities/select-fields](https://docs.openalex.org/how-to-use-the-api/get-lists-of-entities/select-fields)

open_access: Field “is_oa”, “oa_status”, “oa_url”, and “any_repository_has_fulltext”).

Currently, openalexR returns only one field "is_oa" for true/false. "is_oa" true/false does not provide enough info for an article's open access level. 

For example, 
works_from_dois <- oa_fetch(entity = "works", doi = c("https://doi.org/10.1681/asn.2012070664", "https://doi.org/10.1007/s11192-013-1221-3"),  verbose = TRUE)

**Comment by trangdata** [comment]
@yhan818 Thank you for reporting. 🐰  I have been meaning to add **open_access** and **language** columns to the dataframe output too: #118. Glad to know that someone will find it useful. Should be quick to implement. 💨
