### ISSUE TITLE
Need to submit update to cran by 8/16

### ISSUE THREAD

**Issue by yjunechoe** [ropensci/openalexR#136]
@trangdata @massimoaria (In case you weren't already aware): I had neglected to mention in #125 that CRAN wants a resubmission with the patch by **August 16** to keep the package on CRAN. We should be safe if we submit at least a few days before the deadline (CRAN is on vacation till 8/8 anyways).

`usethis::use_release_issue("patch")` puts us at 1.1.3 - does this work or do we want to bump minor (1.2.0) to reflect some new features since 1.1.0 on CRAN? And do we need/want to wrap up any outstanding issues for this update?

(Also @trangdata let me know if you want a copy of the cran mass email for full context!)

**Comment by massimoaria** [comment]
I am on vacation until next week and don't have my PC with me. I will do it next week.

**Comment by massimoaria** [comment]
I think we should release a major version considering all the improvements and new features included in this version.

**Comment by trangdata** [comment]
> usethis::use_release_issue("patch") puts us at 1.1.3 - does this work or do we want to bump minor (1.2.0) to reflect some new features since 1.1.0 on CRAN? And do we need/want to wrap up any outstanding issues for this update?

I'm voting for bumping to v1.2.0 to reflect the new features. I think we're at a good stage for a release. I need more time to experiment with #132 and don't want to break anything in the next release.

> Also @trangdata let me know if you want a copy of the cran mass email for full context!

Thank you, June. I got this email from Massimo already.

**Comment by yjunechoe** [comment]
Great! And @trangdata let me know if you need a hand with the PR (I can write some tests, etc.)

**Comment by trangdata** [comment]
Your help is always welcome @yjunechoe 🪴  but yeah the PR is not a "fix" so I'm not rushing it, but if you do have time, would love to have you take a look!

**Comment by trangdata** [comment]
v1.2.0 is on CRAN. Thank you @massimoaria 💯 🚀  https://cran.r-project.org/web/packages/openalexR/index.html
