### ISSUE TITLE
openAlex APC info

### ISSUE THREAD

**Issue by yhan818** [ropensci/openalexR#148]
Does openAlexR pull out APC info? This info is used by many libraries for collection development. 

For example, openAlex has this info https://api.openalex.org/works/W2985709543 (see apc_list and apc_paid). Will this feature to be developed or integrated?

**Comment by trangdata** [comment]
Hi @yhan818, in the conversion from the list output to dataframe, we currently do not include apc_*. If these fields are important for your project, you can set `output = "list"` which will return a nested list of all fields.

``` r
library(openalexR)
w <- oa_fetch(identifier = "W2985709543", output = "list")
w[c("apc_list", "apc_paid")]
#> $apc_list
#> $apc_list$value
#> [1] 3550
#> 
#> $apc_list$currency
#> [1] "USD"
#> 
#> $apc_list$value_usd
#> [1] 3550
#> 
#> $apc_list$provenance
#> [1] "doaj"
#> 
#> 
#> $apc_paid
#> $apc_paid$value
#> [1] 3550
#> 
#> $apc_paid$currency
#> [1] "USD"
#> 
#> $apc_paid$value_usd
#> [1] 3550
#> 
#> $apc_paid$provenance
#> [1] "doaj"
```

<sup>Created on 2023-08-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>


> This info is used by many libraries for collection development.

Could you elaborate on this? What is the question that these APC fields can answer? Right now I'm leaning toward not adding more columns to the dataframe output unless the field is important to the work itself.

**Comment by yhan818** [comment]
Since you suggested an alternative way to get data, it is not an urgent need to add. 

FYI.  
Article Processing Charges (APC) are used by publishers to fund open access. 

Some already wrote how APC can be used. I also learn that researchers and funders can benefit from this. see https://blog.f1000.com/2020/01/31/how-libraries-and-funders-can-drive-apc-transparency/

Some Universities sponsoring APC for author publishing. see https://guides.library.cmu.edu/apcfund 

For library's common use cases, see https://library.viu.ca/publishingconsiderations/APC
