### ISSUE TITLE
openAlex location info

### ISSUE THREAD

**Issue by yhan818** [ropensci/openalexR#149]
Currently openAlexR only provides location info for DOI and PubMed only. 

OpenAlex original data has more location info. For example, https://api.openalex.org/works/W2985709543

- see "locations": location 0: "is_oa": true, "landing_page_url", and "pdf_url", "host_organization_name", etc. 
- see "best_oa_location": 

This information is important for an institution to evaluate its scholarly publishing efforts. There are other uses of this data. 

Can this feature to be developed? 

Thank you,

**Comment by trangdata** [comment]
We have unpacked a lot of these fields (slightly different names) in the dataframe output, but if you need more extensive results, you can set output = "list" which will return a nested list of all fields.

``` r
library(openalexR)
#> Thank you for using openalexR!
#> To acknowledge our work, please cite the package by calling
#> `citation("openalexR")`.
w <- oa_fetch(identifier = "W2985709543")
w[c("is_oa", "pdf_url", "host_organization", "url")]
#> # A tibble: 1 × 4
#>   is_oa pdf_url host_organization url                              
#>   <lgl> <lgl>   <chr>             <chr>                            
#> 1 FALSE NA      Wiley-Blackwell   https://doi.org/10.1111/tid.13204
```

<sup>Created on 2023-08-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
