### ISSUE TITLE
Obtain impact factor?

### ISSUE THREAD

**Issue by JeffreySmithA** [ropensci/openalexR#172]
I have a relatively large dataset at the paper level (so work ID). In the OpenAlex API documentation, it's possible to obtain the impact factor for every publication via "funder object" or "author object" with "2yr_mean_citedness" but using OA_fetch, I'm only able to search for publications with a certain impact factor, not obtain the impact factor of each publication.

Is this something that's possible with the R package. I tried searching previous questions and documentation but am still struggling. Sorry to be a nuissance!

**Comment by TimothyElder** [comment]
Impact factor is a measure that is applied to scientific journals. If you want to retrieve the impact factor for a source you can use the development version of openalexR by installing from GitHub via this code

```R
install.packages("remotes")
remotes::install_github("ropensci/openalexR")
```
You can find the 2year mean citedness (impact factor), the h-index and i10 index for a journal from the `summary_stats` column from the source:

```R
journal <- oa_fetch(identifier = "S1983995261")
journal$summary_stats
```
If you want to retrieve all the sources for all the articles in your dataset you can fetch on the `so_id` column of your articles data frame.

```
articles <- c("https://openalex.org/W2128728535", "https://openalex.org/W2028302194",
                      "https://openalex.org/W2149609916", "https://openalex.org/W2002799357",
                      "https://openalex.org/W2118526609")

oa_fetch(identifier = articles,
                entities = "sources")

**Comment by trangdata** [comment]
Thank you so much for the clear answer @TimothyElder 💯 . I just wanted to chime in to say that our CRAN release last month v1.2.1 #160 should have this field in the source's `summary_stats` as well.

**Comment by JeffreySmithA** [comment]
Thanks again for being so patient/helpful!
