### ISSUE TITLE
Integration in VOSviewer?

### ISSUE THREAD

**Issue by rkrug** [ropensci/openalexR#173]
Hi

I know about `oa2bibliometrix(df)` for bibliomatrix. Is there something similar to VOSviewer?

Greetings.

**Comment by trangdata** [comment]
Hey @rkrug, no, this is not currently planned but we would love any contribution if you want to make a PR. 🙏🏽

**Comment by rkrug** [comment]
Will think about it...

I will try bibliomatrix than for the moment. Following the example at https://docs.ropensci.org/openalexR/reference/oa2bibliometrix.html - hot do I get that object `M` in biblioshiny?
