### ISSUE TITLE
OpenAlex API request failed [403]

### ISSUE THREAD

**Issue by SimonMontfort** [ropensci/openalexR#202]
using the code from the help file: 

    query4 <- oa_query(
      identifier = NULL,
      entity = "works",
      filter = 'title.search:"bibliometric analysis"|"science mapping"',
      from_publication_date = "2020-01-01",
      to_publication_date = "2021-12-31",
      search = NULL,
      endpoint = "https://api.openalex.org"
    )

    res4 <- oa_request(
      query_url = query4,
      count_only = TRUE,
      verbose = FALSE
    )

I get the following error:

    Error: OpenAlex API request failed [403]
    Invalid query parameters error.
    < is not a valid field. Valid fields are underscore or hyphenated versions of: abstract.search, apc_list.currency, apc_list.provenance, apc_list.value, apc_list.value_usd, apc_paid.currency, apc_paid.provenance, apc_paid.value, apc_paid.value_usd, author.id, author.orcid, authors_count, authorships.author.id, authorships.author.orcid, authorships.countries, authorships.institutions.continent, authorships.institutions.country_code, authorships.institutions.id, authorships.institutions.is_global_south, authorships.institutions.lineage, authorships.institutions.ror, authorships.institutions.type, authorships.is_corresponding, best_oa_location.is_accepted, best_oa_location.is_oa, best_oa_location.is_published, best_oa_location.landing_page_url, best_oa_location.license, best_oa_location.source.host_organization, best_oa_location.source.host_organization_lineage, best_oa_location.source.id, best_oa_location.source.is_i

**I want to build a keyword query using AND and OR to download articles from OA. How can I do so?**

If I uncomment as follows 

    query3 <- oa_query(
      # identifier = NULL,
      entity = "works",
      filter = 'title.search:"bibliometric analysis"|"science mapping"',
      # from_publication_date = "2020-01-01",
      # to_publication_date = "2021-12-31",
      # search = NULL,
      endpoint = "https://api.openalex.org"
    )

    res3 <- oa_request(
      query_url = query3,
      count_only = FALSE,
      verbose = T
    )
    

It seems to be downloading all OA works

`Getting 1242538 pages of results with a total of 248507411 records...
  OpenAlex downloading [---------------------]   0% eta: 17dError in curl::curl_fetch_memory(url, handle = handle) : 
  Operation was aborted by an application callback`

**Comment by SimonMontfort** [comment]
If I construct the query myself, it seems to be working without a problem 

    query1 <- 'https://api.openalex.org/works?filter=abstract.search:("bibliometric analysis" AND "science mapping")'
    oa <- oa_request(
      query_url = query1,
      verbose = TRUE
    )
    oa_works <- oa2df(oa, "works")

**Comment by trangdata** [comment]
Thank you for reporting this. We need to update these examples in `oa_request`. I'll submit a PR.

Because of rewrite early on, there are a few ways we can include in our request these three filters: title.search, from_publication_date and to_publication_date. They can either be independent arguments of the `oa_query` functions, or included as an element of the `filter` argument. For example:

``` r
library(openalexR)
q <- oa_query(
  entity = "works",
  filter = list(
    title.search = '"bibliometric analysis"|"science mapping"',
    from_publication_date = "2020-01-01"
  ),
  to_publication_date = "2021-12-31",
)
r <- oa_request(
  query_url = q,
  count_only = TRUE,
  verbose = FALSE
)
r
#> $count
#> [1] 3989
#> 
#> $db_response_time_ms
#> [1] 105
#> 
#> $page
#> [1] 1
#> 
#> $per_page
#> [1] 1
#> 
#> $groups_count
#> NULL
```

<sup>Created on 2024-02-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I know you're just following the examples in the help file, but fwiw, what I think is most canonical would be:

``` r
library(openalexR)
oa_fetch(
  entity = "works",
  title.search = '"bibliometric analysis"|"science mapping"',
  from_publication_date = "2020-01-01",
  to_publication_date = "2021-12-31",
  count_only = TRUE
)
#>      count db_response_time_ms page per_page
#> [1,]  3989                 105    1        1
```

<sup>Created on 2024-02-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by SimonMontfort** [comment]
Thank you! Though in the oa_fetch example, it is not possible to use AND operators, right?

**Comment by trangdata** [comment]
`oa_fetch` is really just a wrapper around `oa_query` and `oa_request`, so anything you can do with `oa_request` you can do with `oa_fetch` as well. 

In your case:
``` r
library(openalexR)
r <- oa_fetch(
  entity = "works",
  title.search = '("bibliometric analysis" OR "science mapping") NOT "systematic map" AND "artificial intelligence"',
  from_publication_date = "2020-01-01",
  to_publication_date = "2021-12-31"
)
head(r$display_name)
#> [1] "Artificial Intelligence in Health Care: Bibliometric Analysis"                                                                                                         
#> [2] "Role of artificial intelligence in operations environment: a review and bibliometric analysis"                                                                         
#> [3] "Application of artificial intelligence to wastewater treatment: A bibliometric analysis and systematic review of technology, economy, management, and wastewater reuse"
#> [4] "Artificial intelligence and machine learning in finance: Identifying foundations, themes, and research clusters from bibliometric analysis"                            
#> [5] "Artificial intelligence applications in supply chain: A descriptive bibliometric analysis and future research directions"                                              
#> [6] "A bibliometric analysis of worldwide educational artificial intelligence research development in recent twenty years"
```

<sup>Created on 2024-02-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Is this what you want?
