### ISSUE TITLE
Progress bar without verbose

### ISSUE THREAD

**Issue by rkrug** [ropensci/openalexR#215]
Hi

it would be great to have in `oa_fetch()` and `oa_request()` an additional argument named `progress` which would indicate if a progress bar is shown. It could be a character vector, which would make it future proof to include other progress indictor options.

**Comment by rkrug** [comment]
OK - that would work. But in my understanding, `verbose` implies diagnostic output, while `progress` implies convenience / information output. So these are two different things for me. But I see your point.

**Comment by trangdata** [comment]
Ah I see. In my head, `verbose` has a more general meaning, essentially just message outputs of a function to the user. 

I do want to note a few helpful discussions re "verbosity" here:

- https://ropensci.org/blog/2024/02/06/verbosity-control-packages/
- https://github.com/tidyverse/design/issues/42
- https://github.com/ropensci/dev_guide/issues/603
