### ISSUE TITLE
Breaking change in last release?

### ISSUE THREAD

**Issue by rkrug** [ropensci/openalexR#217]
Before the last update, I could do:

```
openalexR::oa_fetch(
            title_and_abstract.search = "biodiversity",
            count_only = TRUE,
            verbose = TRUE
        )[, "count"]
```

which now gives a subscript out of bounds.

**Comment by yjunechoe** [comment]
I actually can't replicate the bug on dev. Could you try running the example again?

I get 

```r
openalexR::oa_fetch(
            title_and_abstract.search = "biodiversity",
            count_only = TRUE,
            verbose = TRUE
        )[, "count"]
#> Requesting url: https://api.openalex.org/works?filter=title_and_abstract.search%3Abiodiversity
#>  count 
#> 267246
```

**Comment by rkrug** [comment]
OK - dev. If I remember correctly, the problem was there when using thew last CRAN release - or was it R-Universe, I really do not remember - sorry. But with the one I am using now, it works. 

```
openalexR   * 1.2.2.9999 2024-03-11 [1] Github (ropensci/openalexR@558581c)
```

**Comment by yjunechoe** [comment]
Good to know we (inadvertently?) fixed a bug that existed previously!
