### ISSUE TITLE
NA becomes `logical(NA)` in conversion not df

### ISSUE THREAD

**Issue by rkrug** [ropensci/openalexR#261]
Hi

May I raise the issue again, that missing fields (experienced again with orchid) become typs=e `logical` if they are not returned from OpenAlex?

I do not have a reproducible example at the moment.

**Comment by trangdata** [comment]
This is a duplicate of #220. I have labeled that issue with high priority. We will get to it soon!

**Comment by rkrug** [comment]
Thanks @trangdata - I looked but overlooked my own issue... Sorry. Next time I will search better.
