### ISSUE TITLE
How to get historical publication/citation data?

### ISSUE THREAD

**Issue by krisgulati** [ropensci/openalexR#268]
Hi,

Is there an easy way to query the API to get historical information on a scholar's publications/citations?

The problem I'm encountering is that I have a scholar in year 2015 with 100 publications and 10,000 citations for example. I would like to get a _similar_ scholar with a similar range (plus or minus 10% of 100 publications/10,000 citations) in the year 2015. 

This is relatively easy when trying to get today's data, but I was just wondering if there is an easier way to do this for many scholars at some point in the past?

Thanks again in advance!

**Comment by trangdata** [comment]
Hi @krisgulati I'm not exactly sure what you mean. Are you using openalexR to do this? Could you give me an example for how you would do this now?

> This is relatively easy when trying to get today's data,

**Comment by krisgulati** [comment]
Currently I'm doing it like this:

"oa_fetch(entity ="authors", works_count =">18", ,works_count ="<22", cited_by_count =">900", cited_by_count ="<1100", last_known_institution.country_code ="US", [x_concepts.id](http://x_concepts.id/) = c("C17744445","C144024400"), options = list(sample = 150, seed = 1))"

This allows me to find matches within certain bounds on scholars **today**.

However, what I would like to do is do a similar matching process but going back historically.

For example, if I have a scholar in 2015 with 1000 citations and 20 papers with their top concepts being x,y,z. I would like to find 20 other scholars - in 2015 - who have the following criteria:

1. Between 900 and 1100 citations (plus or minus 10% of 1000 citations)
2. Between 18 and 22 publications (plus or minus 10% of 20 papers)
3. Similar research (using n concepts as documented above)
4. In 2015

Hopefully this is slightly clearer (apologies)!

**Comment by trangdata** [comment]
Hmm, that is a difficult query... What I think you might be able to do is 
- first query for works with prespecified concepts before 2015 (perhaps going back to 1965, assuming a 50-year academic career for a researcher)
- then group these works by authors
- filter for authors with 18—22 of these works
- filter for authors with 900—1100 citations (will they be citations within these concepts or all citations?)

I would also recommend posting this question on the [OpenAlex Community Google Group](https://groups.google.com/g/openalex-community) to see if others have better ideas!

**Comment by krisgulati** [comment]
Hey,

Thanks for the quick and thoughtful response! We may try your route! In some sense I'm happy that there wasn't an easy solution because it means at least I was trying the right thing :). 

I'll try the Google Group now - thanks for sharing.
