### ISSUE TITLE
oa_fetch () missing additional author's institutions? 

### ISSUE THREAD

**Issue by yhan818** [ropensci/openalexR#270]
I am conducting institutional-level citation analysis. 

There are some cases that an author having multiple affiliations. A parent organization may have multiple child organizations. For example, University of Arizona ROR (https://ror.org/03m2x1q45) have multiple units, including Lunar and Planetary Institute (https://ror.org/01r4eh644)

For certain works, an author has multiple institutions/affiliations associated with the work's metadata in OpenAlex. 

1. If I fetch the work's data using openAlex. 
 `oa_fetch_test1 <-oa_fetch( entity="works",  id="https://openalex.org/W4401226694")`
 `view(oa_fetch_test1[[4]][[1]])`

It has " 2  https://openalex.org/I58286723 Lunar and Planetary Institute https://ror.org/01r4eh644   " only.

2. If going back to openAlex's API https://api.openalex.org/works/W4401226694 
It has both (Lunar and Planetary Institute" and "University of Arizona". 

So oa_fetch() for "works" missing the additional institutions from openAlex's API data? 

![Screenshot from 2024-08-28 15-48-21](https://github.com/user-attachments/assets/f2260f7a-7378-49c8-8965-9c95b196d6a2)

**Comment by yjunechoe** [comment]
If the author has multiple institutions, we track only the first in `$institution_id` but still track all in a flat (comma-separated string) structure in `$institution_lineage`:

```r
oa_fetch_test1$author[[1]][2,]$institution_id
#> [1] "https://openalex.org/I58286723"

oa_fetch_test1$author[[1]][2,]$institution_lineage
#> [1] "https://openalex.org/I1329765538, https://openalex.org/I58286723"
```

So fetching those 2 institution IDs from `$institution_lineage` gets back what you observed:

``` r
oa_fetch_test1$author[[1]][2,]$institution_lineage |> 
  strsplit(", ") |> 
  el(1) |> 
  oa_fetch(entity = "institutions") |> 
  subset(, c("id", "display_name"))
#> # A tibble: 2 × 2
#>   id                               display_name                           
#>   <chr>                            <chr>                                  
#> 1 https://openalex.org/I1329765538 Universities Space Research Association
#> 2 https://openalex.org/I58286723   Lunar and Planetary Institute
```

Ref: https://github.com/ropensci/openalexR/pull/155

**Comment by yhan818** [comment]
Thank you. It will be nice to have all the institutions available. There will be multiple ways to get it implemented, such as list(). or an additional fields

**Comment by trangdata** [comment]
Thank you for this conversation @yhan818 and @yjunechoe. I think OpenAlex used to provide only one affiliation of authors, and when they introduced more affiliations/institutions, we still stick with exporting only the first one for simplicity. But you're right, we could make these list columns.

https://github.com/ropensci/openalexR/blob/774aff7c6160163bd7b28960e864425079b8d5a2/R/oa2df.R#L222-L236

**Comment by trangdata** [comment]
OK so currently, we have the following columns for `author`, where `institution_*` refers to the first institution reported by OpenAlex. 

``` r
oa_fetch_test1 <- openalexR::oa_fetch(entity = "works", id = "https://openalex.org/W4401226694")
oa_fetch_test1$author[[1]] |> 
  dplyr::select(au_affiliation_raw, starts_with("institution"))
#>                                                                                                                                                                      au_affiliation_raw
#> 1                                                                                                                 Department of Astronomy & Astrophysics, University of Toronto, Canada
#> 2                                                                                                                        Lunar and Planetary Laboratory, The University of Arizona, USA
#> 3 Dept. of Physics and Astronomy, Northwestern University, 2145 Sheridan Rd., Evanston, IL 60208 and Center for Interdisciplinary Exploration and Research in Astrophysics (CIERA), USA
#>                    institution_id      institution_display_name
#> 1 https://openalex.org/I185261750         University of Toronto
#> 2  https://openalex.org/I58286723 Lunar and Planetary Institute
#> 3 https://openalex.org/I111979921       Northwestern University
#>             institution_ror institution_country_code institution_type
#> 1 https://ror.org/03dbr7087                       CA        education
#> 2 https://ror.org/01r4eh644                       US         facility
#> 3 https://ror.org/000e0be47                       US        education
#>                                                institution_lineage
#> 1                                  https://openalex.org/I185261750
#> 2 https://openalex.org/I1329765538, https://openalex.org/I58286723
#> 3                                  https://openalex.org/I111979921
```

<sup>Created on 2024-09-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The question is, do we want to include `affiliations` and/or `institutions` as a list column, such that:

``` r
oa_fetch_test1$author[[1]]$affiliations
# [[1]]
# [[1]]$raw_affiliation_string
# [1] "Department of Astronomy & Astrophysics, University of Toronto, Canada"
# 
# [[1]]$institution_ids
# [[1]]$institution_ids[[1]]
# [1] "https://openalex.org/I185261750"
# 
# 
# 
# [[2]]
# [[2]]$raw_affiliation_string
# [1] "Lunar and Planetary Laboratory, The University of Arizona, USA"
# 
# [[2]]$institution_ids
# [[2]]$institution_ids[[1]]
# [1] "https://openalex.org/I58286723"
# 
# [[2]]$institution_ids[[2]]
# [1] "https://openalex.org/I138006243"
# 
# 
# 
# [[3]]
# [[3]]$raw_affiliation_string
# [1] "Dept. of Physics and Astronomy, Northwestern University, 2145 Sheridan Rd., Evanston, IL 60208 and Center for Interdisciplinary Exploration and Research in Astrophysics (CIERA), USA"
# 
# [[3]]$institution_ids
# [[3]]$institution_ids[[1]]
# [1] "https://openalex.org/I111979921"

oa_fetch_test1$author[[1]]$institutions
#> [[1]]
#> # A tibble: 1 × 6
#> id                              display_name          ror                       country_code type      lineage     
#> <chr>                           <chr>                 <chr>                     <chr>        <chr>     <named list>
#>   1 https://openalex.org/I185261750 University of Toronto https://ror.org/03dbr7087 CA           education <list [1]>  
#>   
#>   [[2]]
#> # A tibble: 2 × 6
#> id                              display_name                  ror                       country_code type      lineage     
#> <chr>                           <chr>                         <chr>                     <chr>        <chr>     <named list>
#>   1 https://openalex.org/I58286723  Lunar and Planetary Institute https://ror.org/01r4eh644 US           facility  <list [2]>  
#>   2 https://openalex.org/I138006243 University of Arizona         https://ror.org/03m2x1q45 US           education <list [1]>  
#>   
#>   [[3]]
#> # A tibble: 1 × 6
#> id                              display_name            ror                       country_code type      lineage     
#> <chr>                           <chr>                   <chr>                     <chr>        <chr>     <named list>
#>   1 https://openalex.org/I111979921 Northwestern University https://ror.org/000e0be47 US           education <list [1]>  
```

What do we think? @yjunechoe @yhan818 

According to the [documentation](https://docs.openalex.org/api-entities/works/work-object/authorship-object):

> Each institutional affiliation that this author has claimed will be listed here: the raw affiliation string that we found, along with the OpenAlex [Institution](https://docs.openalex.org/api-entities/institutions) ID or IDs that we matched it to. [affiliations] is redundant with [institutions], but is useful if you need to know about what we used to match institutions.

**Comment by yhan818** [comment]
OpenAlex has changed some outputs quite heavily in 2024. It has new data model and added new entities (e.g. grants). 

In general, maintaining backward compatibility is a good practice. For example, it will not break code developed using the current openAlexR. 

Shall we add a new field (e.g. author's affiliations) and leave the old one untouched?

**Comment by trangdata** [comment]
@yhan818 I agree *generally* it's good practice to maintain backward compatibility, but we do have to balance that out with other factors like cost of maintenance, computation, complexity, etc. I have [shared](https://github.com/ropensci/openalexR/issues/247#issuecomment-2104556609) this view before. To sum up, as a third-party package, I think it's important we try to mirror how OpenAlex changes.

**Comment by rkrug** [comment]
To keep up with OpenAlex changes is a moving target, and openalexR will always be running behind. But one could do the following, to offer both:

1. The default format of fetch is `list` as it is essentially the response coming from OpenAlex, or as an alternative raw json as returned per page saved to files (see #271, https://github.com/ropensci/openalexR/issues/271#issuecomment-2338482943). This would always be backwards compatible.
2. Offer functions which convert, the list or json into a `tibble` which need to be called separately. This makes it possible to have backward compatible functions as well as follow new approaches at a later stage. Also using the son with e.g. duckDB would for example nut require any conversion.

The problem would be step on, i.e. changing a default value, which will break compatibility, but this could be introduces over a few version with deprecation warning.

**Comment by yhan818** [comment]
Agreed with both of you in principle. Given the changes with openAlex, it is not mature. So back-comparability may not be that important. I am fine with either approach.
