### ISSUE TITLE
Vignette: Strategies to optimize performance/memory usage

### ISSUE THREAD

**Issue by trangdata** [ropensci/openalexR#274]
Perhaps we could put together a vignette on different strategies to optimize openalexR's performance and to consolidate the many GH issue threads we have had:
- `select = ...`
- `output = "list"`
- `oa_generate` with save as .rds in chunks for (memory)
- ... (anything else? @yjunechoe)
- link to different issues, explain our thinking re breaking changes, backward compatibility, etc. (maybe this is a different vignette?)

**Comment by yjunechoe** [comment]
Maybe the last bullet point can be a different vignette (broadly covering "Reproducibility", perhaps?) but I agree!

If you want to divide the work I can write up the strategy I wrote about the other day - https://github.com/ropensci/openalexR/issues/271#issuecomment-2338416246. I'm less familiar with the `oa_generate()` strategy though.

**Comment by rkrug** [comment]
I think this is a great idea, but I would advise against `oa_generate()`. I tried to use it, it took me a considerable time to implement it, and then I had a bug somewhere which I did not figure out how to use. 

Adding "each page as json in a directory" would make the use of `oa_generate()` not necessary and, imho, easier to maintain. The usage of the data in that directory would be completely to the advanced user. But I really like this idea of a vignette on this topic.

**Comment by trangdata** [comment]
> If you want to divide the work I can write up the strategy I wrote about the other day - [#271 (comment)](https://github.com/ropensci/openalexR/issues/271#issuecomment-2338416246)

That would be great! Do you want to start the vignette? and I will add the `oa_generate` part after? Thanks so much June!
