### ISSUE TITLE
How long does it take to pull 10,000 records?

### ISSUE THREAD

**Issue by trangdata** [ropensci/openalexR#278]
A repost of [Yan's question](https://github.com/ropensci/openalexR/issues/271#issuecomment-2364735002) @yhan818:

Hi, I ran your code to fetch all the fields. 

malaria_topic <- oa_fetch(entity = "topics", search = "malaria") %>% 
  filter(display_name == "Malaria") %>% 
  pull(id)
malaria_topic
#> [1] "https://openalex.org/T10091"

system.time({
  res <- oa_fetch(
    topics.id = malaria_topic,
    entity = "works",
    verbose = TRUE,
    options = list(sample = 1000, seed = 1),
    output = "list"
  )
})

It took 76 seconds to pull out all the fields (40 seconds to pull out the select fields)

I used the following code to fetch 10,000 records. It took 260 seconds). The only add-on is the batch_identifiers array.  Any thoughts? 

system.time({
  batch_identifiers <-org_ref_works_cited[1:10000]
  res <-oa_fetch(identifier=batch_identifiers, 
                 entity = "works",
                 options= list(sample=10000, seed=1), 
                 output="list")
})

**Comment by trangdata** [comment]
Hi Yan,

Is it possible you're running this on an older version of R? I ran this on v4.2.1 and it's a lot faster than what you had (<9s to pull 1000 records, 106s to sample 10,000 records).

``` r
library(openalexR)

system.time({
  res <- oa_fetch(
    topics.id = "T10091",
    entity = "works",
    verbose = TRUE,
    options = list(sample = 1000, seed = 1),
    output = "list"
  )
})
#> Requesting url: https://api.openalex.org/works?filter=topics.id%3AT10091&sample=1000&seed=1
#> Getting 5 pages of results with a total of 1000 records...
#>    user  system elapsed 
#>   1.716   0.102   8.466

system.time({
  res <- oa_fetch(
    entity = "works",
    options = list(sample = 10000, seed = 1),
    output = "list",
    verbose = TRUE
  )
})
#> Requesting url: https://api.openalex.org/works?sample=10000&seed=1
#> Getting 50 pages of results with a total of 10000 records...
#>    user  system elapsed 
#>  10.661   0.496 106.102
```

<sup>Created on 2024-09-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by yhan818** [comment]
Hi, Trang, 

Thank you for the suggestion. My previous result was run under R version 4.1.2 (2021-11-1). Under it, it took 260 seconds). 

I upgraded R to the latest version 4. 4.1 (2024-06-14). Ran the above code again. It took 112 seconds. 

This is interesting! I will re-run the code for oa_fetch().
