### ISSUE TITLE
Is it possible to sample only a subset of works when using oa_snowball ?

### ISSUE THREAD

**Issue by adrientaudiere** [ropensci/openalexR#279]
Hi all,
Thanks for your very usefull package. 

I wonder if it is possible to add  an equivalent of `options = list(sample = 10, seed = 1))` to each snowball query ? For the moment if I add ` options = list(sample = 10, seed = 1)`, it only apply to the first oa_fetch query. And the option `citing_params` and `cited_by_params` add a filter in the api request, so the api parameter _sample_ is not usable. 

Best,

**Comment by trangdata** [comment]
Hi @adrientaudiere could you elaborate on the motivation to perform such an analysis? Why would you want a subset of the cited/citing work?

**Comment by adrientaudiere** [comment]
Hi @trangdata, 
I run some "big" analysis, and sometimes I only want to perform the analysis on a small subset of random work to test the entire pipeline with a few works. I know that I can filter the dataset after snowball, but when I saw the option `sample` in `oa_fetch`, I thank that it would be useful to be able to add sample in `oa_snowball`.  It's only a small feature request, I understand that it is not very important (-;.

**Comment by yjunechoe** [comment]
The idea is not completely out of scope, but I'd also like to hear more before considering implementing this (though it seems like sampling, specifically, is not the point?)

If the point is to test a pipeline with a small `oa_snowball()` output, I'd probably prefer using the `to/from_publication_date` filter in the citing/cited_by params - this is how we also write our own tests for `oa_snowball()`! That will also give you a *stable* subset to work with (unless you're specifically looking to test against output variability?).
```r
library(openalexR)

x <- oa_fetch(doi = "10.1038/s41586-022-05258-z")

# >200 connections
x$cited_by_count + length(x$referenced_works[[1]])
#> [1] 221

# Search the range of 1 year forward, 10 years back
pub_date <- as.Date(x$publication_date)
snowball <- oa_snowball(
  identifier = x$id,
  citing_params = list(to_publication_date = as.character(pub_date + 365)),
  cited_by_params = list(from_publication_date = as.character(pub_date - 3650))
)

# Returns a subset
nrow(snowball$nodes)
#> [1] 112

hist(as.Date(snowball$nodes$publication_date), "years", freq = TRUE)
abline(v = pub_date, col = "red", lwd = 3)
```

![image](https://github.com/user-attachments/assets/51e07c0a-9f3a-48bf-bbec-3381b5d6c07a)

**Comment by adrientaudiere** [comment]
Oh yes, it's a perfect trick. Maybe it deserves to be present in the example of the function. Thank you.

**Comment by yjunechoe** [comment]
> Oh yes, it's a perfect trick. Maybe it deserves to be present in the example of the function. Thank you.

We had actually planned for a full snowballing _vignette_ but haven't got around to it. We'll keep this example in mind!

**Comment by yjunechoe** [comment]
Update: no longer necessary to do date conversion of `publication_date` in dev

```r
library(openalexR)

x <- oa_fetch(doi = "10.1038/s41586-022-05258-z")

# >200 connections
x$cited_by_count + length(x$referenced_works[[1]])
#> [1] 223

# Search the range of 1 year forward, 10 years back
snowball <- oa_snowball(
  identifier = x$id,
  citing_params = list(to_publication_date = x$publication_date + 365),
  cited_by_params = list(from_publication_date = x$publication_date - 3650)
)

# Returns a subset
nrow(snowball$nodes)
#> [1] 114

hist(snowball$nodes$publication_date, "years", freq = TRUE)
abline(v = x$publication_date, col = "red", lwd = 3)
```

![image](https://github.com/user-attachments/assets/8da920e9-a3ac-4f8b-ac9e-7691e3edc879)

Closing to track vignette discussion in #284
