### ISSUE TITLE
Missing "host_organization" (not available anymore) 

### ISSUE THREAD

**Issue by yhan818** [ropensci/openalexR#295]
Looks like the column "host_organization" is no longer available.  This is the field next to "so_id" (now called "source_id") 
I think this is the only field no there after the refactoring? 

Please try and compare with previous version. 

UAUMC.df <-oa_fetch(
  entity="works",
  institutions.ror=c("02xbk5j62"),
  from_publication_date ="2024-01-01")

**Comment by trangdata** [comment]
OK host_organization and host_organization_name are now added back in 2bb285cc31e67ffac2c3deb55e80fe0e0ca4c79d

**Comment by yhan818** [comment]
Yes. "host_organization" is very important for institutions to analyze publishers' journals citations and usage. It serves for at least 2 purposes: 1) to understand where authors publish their works; 2) to understand and analyze publishers' journals usage (for collection management).

**Comment by yhan818** [comment]
> OK host_organization and host_organization_name are now added back in [2bb285c](https://github.com/ropensci/openalexR/commit/2bb285cc31e67ffac2c3deb55e80fe0e0ca4c79d)

Will you release it in CRAN? If not, what is the timeline?

**Comment by trangdata** [comment]
#211 is now ready for review, so I expect it'll be merged to main in a few days.

The current version of openalexR on cran should still have the old behavior (with host_organization). I hope to push the 2.0.0 release to cran once everything is in place! CC @massimoaria

**Comment by trangdata** [comment]
Closed by #211
