### ISSUE TITLE
Only pulling the first "last_known_institution"

### ISSUE THREAD

**Issue by philiplindsay** [ropensci/openalexR#304]
Hello! Thanks for your package, and excited to submit my first issue.

I found that in authors2df, only the first of last_known_institution is pulled:

`    sub_affiliation <- item$last_known_institutions
    if (!is.null(sub_affiliation) && length(sub_affiliation)) {
      sub_affiliation <- sub_affiliation[[1]]
      if (is.na(sub_affiliation[[1]])) {
        sub_affiliation <- empty_inst
      }`

This is problematic in cases where researchers have multiple current affiliations, such as medical researchers at institutions with AMCs, where they will both be affiliated with the main campus and the healthcare affiliate. Is there a way to update this function so all the "affiliation" variables are a list that includes every current affiliation? In most cases, this will only be one item.

One example of where the assumption really breaks down is with Brown University, where an error in the fuzzy matching algorithm on the OpenAlex team's side has caused "Providence College" to be an affiliation for nearly every Brown researcher. Often "affiliation" for these researchers will be Providence, and I would love an easy way to still run analyses despite that bug. Example here: [https://openalex.org/authors?page=1&filter=last_known_institutions.id%3Ai27804330]

**Comment by trangdata** [comment]
Hi Philip 👋🏽  Thanks for submitting this! We actually had updated `authors2df` recently (see [NEWS](https://github.com/ropensci/openalexR/blob/main/NEWS.md)). We need to make a new release (v2.0.0) to CRAN soon (after hopefully tackling a few more issues). Could you try installing the dev version and let me know if it works as you would expect? 

```r
install.packages("remotes")
remotes::install_github("ropensci/openalexR")
```

**Comment by philiplindsay** [comment]
Works like a charm! Thanks for the wildly quick response. As a small piece of feedback, I did find the old variable ("other_affiliations" with the historical affiliations) to be pretty interesting when we are exploring trends in our faculty turnover (e.g., which institutions tend to poach our top faculty members). But I realize the variables included in the formatted data frame are the absolute most important, so recognize there are reasons to prioritize! Thanks for this wonderful update!!
