### ISSUE TITLE
Retrieving works associated with a specific topic

### ISSUE THREAD

**Issue by rgoldsto** [ropensci/openalexR#307]
How would I use openalexR to fetch all of the works that are associated with a particular topic?  I understand how to retrieve all works that have a particular phrase in the title, but I'm confused because the "topics" structure associated with a work is a list, not a single value.  The code below works to retrieve works with a particular PRIMARY topic:
works_search <- oa_fetch(
  entity = "works",
  primary_topic.id="T12694",
  verbose = FALSE
)

But doesn't work if one wants to retrieve works with topic T12694 as ANY of the listed topics.

Thanks for any suggestions!

**Comment by trangdata** [comment]
Hi @rgoldsto — Looks like you can also [filter works](https://docs.openalex.org/api-entities/works/filter-works) by `topics.id` which includes the top ranked [Topics](https://docs.openalex.org/api-entities/topics) for a work. Is this what you wanted?

``` r
library(openalexR)
w <- oa_fetch(
  entity = "works",
  topics.id = "T12694",
  options = list(sample = 10, seed = 1)
)

w$topics[[1]]
```

**Comment by rgoldsto** [comment]
Thanks, @trangdata!  You're right - it looks like the topics.id filter checks to see whether any of the topics associated with the work match the requested ID.  That'll work great for my purposes!
