### ISSUE TITLE
Add grouping to reference index page?

### ISSUE THREAD

**Issue by maelle** [ropensci/openalexR#87]
See https://pkgdown.r-lib.org/reference/build_reference.html#reference-index 

Having grouping, rather than alphabetical order, on the pkgdown reference index, can improve users' experience.

This is only a suggestion. :smile_cat:

**Comment by trangdata** [comment]
Great suggestion @maelle!!! Completely agreed this small change would be very useful!

**Comment by maelle** [comment]
The PR didn't close this, see https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword (I'd have thought "Adresses" was a keyword but it's not)

**Comment by trangdata** [comment]
I have been wrong all this time! 😨  Closing manually.
