### ISSUE TITLE
Authors' display name is exact match. Is there any way to do a fuzzy search ? 

### ISSUE THREAD

**Issue by yhan818** [ropensci/openalexR#89]
For your code example searching authors' name. You have the code "entity = "authors", display_name = c("Massimo Aria", "Jason Priem"), The display_name is an exact match. 

However, there are authors who have middle names. If the middle name is in OpenAlex's dataset, the search will return nothing. I have identified a few authors who have middle name listed. 

Is your package allow search something like "Massimo * Aria"? (where * can be 0 or more characters for the middle name).

**Comment by trangdata** [comment]
Hi @yhan818, I don't think we have regex matching, but perhaps `search` is the argument you can use?

``` r
library(openalexR)

au_result <- oa_fetch("author", search = "Massimo Aria")
au_result[, c(1,2,10)]
#> # A tibble: 9 × 3
#>   id                               display_name      affiliation_display_name   
#>   <chr>                            <chr>             <chr>                      
#> 1 https://openalex.org/A923435168  Massimo Aria      University of Naples Feder…
#> 2 https://openalex.org/A4271282346 None Massimo Aria <NA>                       
#> 3 https://openalex.org/A2098709409 Massimo Aria      <NA>                       
#> 4 https://openalex.org/A4297506000 MASSIMO ARIA      <NA>                       
#> 5 https://openalex.org/A4305704731 Aria, Massimo     <NA>                       
#> 6 https://openalex.org/A4307035467 Massimo Aria      University of Naples Feder…
#> 7 https://openalex.org/A4317516865 Massimo Aria      <NA>                       
#> 8 https://openalex.org/A4320733092 Massimo Aria      University of Naples Feder…
#> 9 https://openalex.org/A4322170729 Massimo Aria      Federico II University Hos…
```

<sup>Created on 2023-03-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by yhan818** [comment]
Thank you very much. This option works. Will you have some documentation to these choices (or I missed the documentation somewhere?)

**Comment by trangdata** [comment]
@yhan818 We don't have an example for this use case in the readme. The `search` argument is documented in [oa_fetch](https://docs.ropensci.org/openalexR/reference/oa_fetch.html) and also `display_name.search` is one of the possible filters for authors: https://docs.ropensci.org/openalexR/articles/Filters.html#authors. If you think this is a really common use case, we would really appreciate a PR of a new article/vignette! 🙏🏽

**Comment by yhan818** [comment]
Thank you. I created a PR in a new branch.
