### ISSUE TITLE
Search filters do not support the | operator

### ISSUE THREAD

**Issue by trangdata** [ropensci/openalexR#94]
It seems that OpenAlex recently changed their API, and an example in our readme no longer works, which is a bummer — I was really enjoying using OR in search. There must be a reason behind this rationale. To be investigated.

CC @ozgur-ozer

``` r
library(openalexR)

works_search <- oa_fetch(
  entity = "works",
  title.search = c("bibliometric analysis", "science mapping"),
  cited_by_count = ">50",
  from_publication_date = "2020-01-01",
  to_publication_date = "2021-12-31",
  sort = "cited_by_count:desc",
  verbose = TRUE
)
#> Requesting url: https://api.openalex.org/works?filter=title.search%3Abibliometric%20analysis%7Cscience%20mapping%2Ccited_by_count%3A%3E50%2Cfrom_publication_date%3A2020-01-01%2Cto_publication_date%3A2021-12-31&sort=cited_by_count%3Adesc
#> Error: OpenAlex API request failed [403]
#> Invalid query parameters error.
#> <Search filters do not support the | operator. Problem value: bibliometric analysis|science mapping>
```

<sup>Created on 2023-04-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by trangdata** [comment]
Watching [release notes](https://github.com/ourresearch/openalex-guts/blob/main/files-for-datadumps/standard-format/RELEASE_NOTES.txt) 👀

**Comment by trangdata** [comment]
@ozgur-ozer Casey has turned this functionality back on. You should no longer receive this error.

**Comment by ozgur-ozer** [comment]
Thanks, @trangdata.
